spring:
  application:
    name: crew
  #JPA
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://retripstudydb.cv4sss0i0mk8.ap-southeast-2.rds.amazonaws.com:3306/crew?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
    open-in-view: false
#logging
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web.client.RestTemplate: DEBUG

springdoc:
  swagger-ui:
    use-root-path: true
